CREATE TABLE ufo
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    location        VARCHAR(255),
    sighting_date   date,
    color           VARCHAR(255),
    shape           VARCHAR(255),
    quntity_objects INTEGER                                 NOT NULL,
    CONSTRAINT pk_ufo PRIMARY KEY (id)
);